# ==================
# gcc-debugoptimized
# ==================

[profile]
desc = GCC debugoptimized: ASan/UBSan + optimized debug build + tests/examples

[build]
dir = build_gcc_debugoptimized
app_rel = src/app/idet/idet_app
