# ===========
# clang-debug
# ===========

[built-in options]
cpp_std = 'c++17'
buildtype = 'debug'
warning_level = '3'
werror = false

b_ndebug = 'false'
b_sanitize = 'address,undefined'
b_lundef = true
b_asneeded = true
b_lto = false

c_args = ['-fno-omit-frame-pointer', '-fno-optimize-sibling-calls', '-fno-sanitize-recover=undefined']
cpp_args = ['-fno-omit-frame-pointer', '-fno-optimize-sibling-calls', '-fno-sanitize-recover=undefined']

[project options]
cpu_opt = 'generic'
fast_math = false
thinlto = false
use_openmp = true
use_numa = true
strict_warnings = true
build_tests = true
build_examples = true
