# ========
# gcc-perf
# ========

[built-in options]
cpp_std = 'c++17'
buildtype = 'release'
warning_level = '2'
werror = false

b_ndebug = 'true'
b_sanitize = 'none'
b_lundef = true
b_asneeded = true
b_lto = true

[project options]
cpu_opt = 'native'
fast_math = true
thinlto = false
use_openmp = true
use_numa = true
strict_warnings = true
build_tests = false
build_examples = false
